### ISSUE TITLE
Tuesday 5/22 - ToDo Beta Blockers

### ISSUE THREAD

**Issue by bgeltz** [geopm/geopm#252]
1. [x] Brad - Bits in the counters.

2. [x] Chris - Changelog.

3. [x] Diana - Man pages for agents need to be made uniform/corrected.  Need warnings about what's implemented in the way it's documented and what isn't.

4. [x] Brad - Klocwork issues. IPLDT. Protex?

5. [x] Chris/Brandon - Merge patch for fixing frequency reporting.  Also fix the unit tests.

6. [x] Brandon - Report time in a way that's equivalent to the way that energy is reported for the regions.

7. [x] Diana - CLANG build (#248).  Low priority.

8. C Interfaces for PlatformIO and PlatformTopo (#247).  Push to post beta.

9. [x] Brad - Remove docu around MPIEXEC usage.  Remove plugin developer's guide.

10.  [x] Brandon/Brad - Nice to haves: Run the tutorials!  Hang in agent tutorial with Intel at the end...

11. Chris - Bash test harness for Endpoint API.  Push to post-beta.

12. [ ] Chris - OpenHPC submission - msrsafe packaging (SLES build), prun integration
