### ISSUE TITLE
Beta Hot Fix Checklist

### ISSUE THREAD

**Issue by bgeltz** [geopm/geopm#269]
- [ ] Frequency reporting issues - #244.  Examine usage with Energy Efficient Agent.
- [ ] Governing Agent - #264.
- [ ] Energy Efficient Agent augmentation for max/min frequencies - #243.
- [x] Override IOGroup signal names - #263.
- [ ] Wiki release checklist.
