### ISSUE TITLE
As a GEOPM HPC Runtime user I would like to be able execute non-MPI applications

### ISSUE THREAD

**Issue by cmcantalupo** [geopm/geopm#2769]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I am unable to use the GEOPM HPC Runtime with an application that either does not use MPI, or does not obey the CPU pinning requirements of the GEOPM HPC Runtime.

**Describe the solution you'd like**
As a first step to support non-MPI applications, it would be great if we could track when an application begins and when it ends independently of the MPI_Init() and MPI_Finalize() PMPI wrappers.  A simple solution is to enable the GEOPM service to provide a registry that maps a "profile name" to a set of Linux PID numbers.  This registry could be used to determine when an application begins and when it ends. 

Over time we can add more features to this use case.  We will still rely on the PMPI wrappers for other start-up, shutdown, and feedback features of the GEOPM HPC Runtime.  This feature request will only provide the mechanism to determine start and end time for a multi-process application.

**Describe alternatives you've considered**
Other solutions might use the HPC resource manager to track application lifetime.  The downsides of this being a dependency on a particular resource manager implementation.  

**Additional context**
A prototype of this feature is posted here:
https://github.com/geopm/geopm/pull/2734

**Tasks**

- [x] Publish the `ServiceProxy` C++ interface as part of the `geopm-service` installed header files
- [x] Add a `SDBus::call_method()`` to support DBus APIs that have a single string input parameter
- [x] Add three new methods to the `ServiceProxy` interface: `platform_start_profile()`, `platform_stop_profile()` and `platform_get_profile_pids()`
- [x] Add new `geopm_pio_*` wrappers for new DBus APIs: `geopm_pio_start_profile()`, `geopm_pio_stop_profile()`, and `geopm_pio_profile_pids()`
- [x] Update dbus_xml.py to support new DBus interfaces: `PlatformStartProfile`, `PlatformStopProfile`, and `PlatformGetProfilePids`
- [x] Update `geopmdpy/system_files.py` to write profile name into session file when profiling starts and remove it when profiling ends
- [x] Use ActiveSessions object to implement `PlatformService` methods `start_profile()`, `stop_profile()`, and `get_profile_pids()`
- [x] Create a new shared object library to be loaded by client applications to support profiling, this will be preloaded instead of libgeopm.so
- [x] Modify `launcher.py` so that libgeopmload.so is preloaded for the client application and *not* preloaded for geopmctl application
- [x] Add a new geopm launch command line option to disable mpi requirement (GEOPM_TIMEOUT=-1 is used in prototype)
- [x] Modify `ApplicationIO` `connect()` and `do_shutdown()` implementations to use new ServiceProxy APIs
- [x] Modify `ApplicationIO` so that ApplicationSampler member is unused when MPI is disabled
- [x] Modify `Profile:init()` implementation to noop when MPI is not enabled
- [x] Modify `SampleAggregator` so that the application feedback is not used for the Application Totals section of the report
- [x] Add library constructor and destructor methods that call `geopm_pio_start_profile()` and `geopm_pio_stop_profile()` for libgeopmload.so
- [x] #2852
- [x] #2853

**Comment by avilcheslopez** [comment]
Duplicates #2875 (defines a subset of the features)
