### ISSUE TITLE
System Characterization Tests

### ISSUE THREAD

**Issue by cmcantalupo** [geopm/geopm#3175]
- [ ] ConstConfig IO can consume a dummy file and provide related signals via geopmread
- [x] ParRes dgemm and nstream build using the ```./build.sh oneapi``` script & option
- [x] #3189
- [x] ParRes dgemm and nstream run successfully without GEOPM - not discussed in current docs, added int #3183 
- [x] gen_pals generates gpu_frequency sweep pbs scripts for ParRes dgemm and nstream  - minor doc update in #3183
- [ ] The GPU Frequency control requested is correct in the associated GEOPM reports - GPU CA integration tests do not explicitly check this.
- [ ] The GPU CA Analysis script generates a const config file based on the GPU Frequency sweep reports - directions on how to generate are in the GPU-CA docs.  Consolidation with other steps into the HOW-TO section may be needed, see #3183.  
- [ ] Const Config IO can consume the GPU characterization file and provide the signals via GEOPM read - no explicit test exists.
- [ ] AIB builds using the ./build.sh script - not discussed in docs.  Added in #3183 
- [x] gen_pals generates a cpu_frequency sweep pbs script for AIB - covered in CPU-CA docs and integration tests
- [ ] The CPU frequency control requested is correct in the associated GEOPM reports - not explicitly checked in integration tests
- [ ] The CPU CA Analysis script generates a const config file based upon the CPU Frequency sweep reports - discussed in CPU-CA docs, may consolidate pointers in HOW-TO section
- [ ] Const Config IO can consume the CPU characterization file and provide the signals via GEOPM read - no explicit test currently exists
- [ ] Uncharacterized nodes provide a LEVELZERO signals for efficient frequency - no explicit integration test currently exists, may need to be a one-off for systems of interest.
- [x] #3232

**Comment by lhlawson** [comment]
Next Steps
1. Document any existing content that completes the above tasks
2. If content doesn't exist, file an issue and create it. 
3. Run content on test system.
4. Automate and/or document the steps required to run test content & confirm pass/fail
5. Run content on target system.
