### ISSUE TITLE
Perform release checklist

### ISSUE THREAD

**Issue by bgeltz** [geopm/geopm#3390]
> estimate 1
Parent [feature/story]: #3384 

Done criteria:
- [x] Re-check ABI compatibility
- [x] Perform required security scans, address any issues
- [x] Notify stakeholders and users about upcoming release and how features differ from 3.0.1 (e.g. GEOPM_PROGRAM_FILTER changing from opt-out to opt-in).
- [x] Also notify users about support plans for 3.0.1 after 3.1 (i.e. no support).
- [x] Update the changelog and README
- [x] Determine which sets of IOGroups will be enabled for upstream GEOPM packages (e.g. L0 for Red Hat, NVML for debian?) 
- [ ] Post-release: Update launchpad, pypi, internal systems, release tarball on GitHub, update the geopm.github.io website...
